name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        continue-on-error: true

      - name: Dump context
        if: success()
        env:
          COMMENT_CONTEXT: ${{ toJson(steps.comment-branch.outputs) }}
        run: echo "$COMMENT_CONTEXT"

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        if: success()
        id: slash-command
        with:
          token: ${{ secrets.ACCESS_PAT }}
          commands: |
            lockfiles
          permission: write
          issue-type: pull-request
          dispatch-type: workflow
          static-args: ref=${{ steps.comment-branch.outputs.head_ref }}
